FROM debian

ARG VER

RUN apt-get update
RUN apt-get install -y ruby ruby-dev rubygems build-essential rpm
RUN gem install --no-document fpm
COPY ./packaging /packaging
COPY ./yeti-discover /
WORKDIR /packaging
RUN /packaging/package.sh ${VER}