FROM debian

ARG VER

RUN apt-get update && apt-get install \
    -y --no-install-recommends \
    ruby ruby-dev rubygems build-essential rpm git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
RUN gem install --no-document fpm
COPY ./packaging /packaging
COPY ./cmon /
WORKDIR /packaging
RUN /packaging/package.sh ${VER}
