name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Build yeti-discover binary
      run: make docker
      
    - name: Build distroless image
      run: |
          docker build --build-arg GOOS=linux -t yeti-discover:${{ github.sha }} -f Dockerfile-distroless .
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
          image-ref: 'yeti-discover:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'

    - name: Upload Trivy Scan Resulte to GitHub SecTab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: 'trivy-results.sarif'
